default_context:
  project_name: visual_coding_2p_analysis
  repo_url: https://github.com/AllenInstitute/visual_coding_2p_analysis
  project_slug: visual_coding_2p_analysis
  user_name: nicholasc
  project_short_description: Visual Coding 2P analysis code
  project_namespace: ''
  version: 0.1.0
  full_name: Nicholas Cain
  _template: git@github.com:AllenInstitute/pyproject_template
  _copy_without_render:
  - docs/aibs_sphinx
  email: nicholasc@alleninstitute.org
